name: vidakids_clientesv4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: assets/icon/logoVDK.png
  adaptive_icon_background: assets/icon/logoVDK.png

flutter:
  uses-material-design: true

assets:
  - assets/